services:
  cadastro_postos:
    build:
      context: ./cadastro_postos
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - rede_recarga
    environment:
      - SERVICE_PORT=8081

  cadastro_usuarios:
    build:
      context: ./cadastro_usuarios
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - rede_recarga
    environment:
      - SERVICE_PORT=8082

  controle_recargas:
    build:
      context: ./controle_recargas
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - rede_recarga
    environment:
      - SERVICE_PORT=8083
    depends_on:
      - cadastro_usuarios
      - cadastro_postos
      - controle_estacoes
      - controle_cobrancas

  controle_estacoes:
    build:
      context: ./controle_estacoes
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - rede_recarga
    environment:
      - SERVICE_PORT=8084

  controle_cobrancas:
    build:
      context: ./controle_cobrancas
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - rede_recarga
    environment:
      - SERVICE_PORT=8085

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - rede_recarga
    depends_on:
      - cadastro_postos
      - cadastro_usuarios
      - controle_recargas
      - controle_estacoes
      - controle_cobrancas

networks:
  rede_recarga:
    driver: bridge
